In [1]:
import numpy as np


In [2]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[50, 28],
       [39, 30],
       [ 5,  2],
       [95, 82],
       [29, 69],
       [67, 44],
       [71, 99],
       [81, 82],
       [61,  5],
       [12, 53]])

In [7]:
scaler_model = MinMaxScaler()

In [8]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
scaler_model.fit(data)

C:\Users\ptdem\anaconda3\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
scaler_model.transform(data)

array([[0.5       , 0.26804124],
       [0.37777778, 0.28865979],
       [0.        , 0.        ],
       [1.        , 0.82474227],
       [0.26666667, 0.69072165],
       [0.68888889, 0.43298969],
       [0.73333333, 1.        ],
       [0.84444444, 0.82474227],
       [0.62222222, 0.03092784],
       [0.07777778, 0.5257732 ]])

In [11]:
scaler_model.fit_transform(data)

C:\Users\ptdem\anaconda3\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.5       , 0.26804124],
       [0.37777778, 0.28865979],
       [0.        , 0.        ],
       [1.        , 0.82474227],
       [0.26666667, 0.69072165],
       [0.68888889, 0.43298969],
       [0.73333333, 1.        ],
       [0.84444444, 0.82474227],
       [0.62222222, 0.03092784],
       [0.07777778, 0.5257732 ]])

In [14]:
import pandas as pd

In [20]:
mydata = np.random.randint(0,101,(50,4))

In [21]:
mydata

array([[ 55,  33,  33,  87],
       [ 49,  85,  14,  23],
       [ 91,  20,  77,  48],
       [ 69,  33,  55,  67],
       [ 55,  32,  20,  58],
       [ 28,  18,  13,  33],
       [  2,   4,  95,  49],
       [ 21,   9,  92,  11],
       [ 77,  38,  95,   6],
       [  6,   0,  26,  38],
       [ 19,   9,  58,  45],
       [ 47,  54,  55,   6],
       [ 79,  26,  84,  55],
       [ 66,  27,  52,   9],
       [  7,  80,  98,  87],
       [ 54,   2,  95,  17],
       [ 86,  18,  57,  49],
       [ 98,   1,  99,  35],
       [ 34,  81,  26,  18],
       [ 27,  78,  18,  20],
       [ 44,   6,  93,  34],
       [ 59,   2,  52,   5],
       [ 60,  46,  78,  39],
       [ 22,  33,  72,  83],
       [ 36,  76,  48,  39],
       [ 78,  37,  86,  73],
       [ 44,  41,  56,  68],
       [ 73,  78,  32,  59],
       [ 59,  72,   0,   1],
       [ 89,  73,  44,  31],
       [ 81,  73,  89,  93],
       [ 99,   8, 100,  97],
       [ 57,  76,  77,  86],
       [ 62,  64,  16,  59],
       [ 76,  

In [29]:
df = pd.DataFrame(data=mydata,columns = ['f1','f2','f3','label'])

In [30]:
df

f1  f2   f3  label
0    55  33   33     87
1    49  85   14     23
2    91  20   77     48
3    69  33   55     67
4    55  32   20     58
5    28  18   13     33
6     2   4   95     49
7    21   9   92     11
8    77  38   95      6
9     6   0   26     38
10   19   9   58     45
11   47  54   55      6
12   79  26   84     55
13   66  27   52      9
14    7  80   98     87
15   54   2   95     17
16   86  18   57     49
17   98   1   99     35
18   34  81   26     18
19   27  78   18     20
20   44   6   93     34
21   59   2   52      5
22   60  46   78     39
23   22  33   72     83
24   36  76   48     39
25   78  37   86     73
26   44  41   56     68
27   73  78   32     59
28   59  72    0      1
29   89  73   44     31
30   81  73   89     93
31   99   8  100     97
32   57  76   77     86
33   62  64   16     59
34   76  40   50      4
35  100  46   48     27
36   25   8   74     31
37   58  27   36     94
38   91  13   84     33
39   67  32   14     80
40   84  45    1     61
41   70   9   55     65
42   17   7   76     94
43   22  11   88     35
44   98  14   31     74
45   76  54   27     17
46   25  28    1     40
47   87  36    4     80
48   34   5   54     59
49   22  60   58     92

In [31]:
X = df[['f1','f2','f3']]

In [36]:
y = df['label']

In [35]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [38]:
X_train.shape

(35, 3)

In [40]:
X_test.shape

(15, 3)