In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.10.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World ")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

b'Hello World '


In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [12]:
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [14]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [17]:
result

30

In [18]:
const = tf.constant(10)

In [19]:
fill_mat = tf.fill((4,4),10)

In [20]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
myrandn = tf.random_normal((4,4), mean=0,stddev=1.0)

In [24]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [26]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [27]:
sess = tf.InteractiveSession()

In [31]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.389872    0.13759838  0.28655767  1.2509129 ]
 [ 0.99701625 -1.2916727  -0.7458927   1.0642238 ]
 [-0.16403963 -0.07837127 -0.80145824  0.36099312]
 [ 1.8482264  -0.11474477 -0.95500195  0.2985678 ]]


[[0.83919036 0.27913082 0.8785213  0.09326565]
 [0.8230258  0.169631   0.02509153 0.93894255]
 [0.9034872  0.41723228 0.73717284 0.8154805 ]
 [0.8926767  0.05257869 0.76749504 0.15767002]]




In [32]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [33]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [34]:
b = tf.constant([ [10] , [100]])

In [35]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
result = tf.matmul(a,b)

In [37]:
sess.run(result)

array([[210],
       [430]])

In [38]:
result.eval()

array([[210],
       [430]])